### ISSUE TITLE
Build ChessRulesEngine

### ISSUE THREAD

**Issue by Alemkin** [ToroCraft/ToroChess#1]
It will be an engine that accepts a list of chess objects that have three properties: (Engine.Type, Engine.Position, Engine.Side), and a chess object that you want to find legal moves for, and it will calculate all legal moves and return  an array of those Engine.Positions that are legal for the provided chess object to move to. 

The front end using this will implement it's entities to have this object on them defining these properties that is kept up to date, and it will do what it will with the returned array.

**Comment by frodare** [comment]
I just pushed a new engine package: https://github.com/ToroCraft/ToroChess/tree/master/java/net/torocraft/chess/engine

Take a look and see if will work. Once we have something everyone agrees on I can start programming the pieces to use the interface.

**Comment by Alemkin** [comment]
I updated it to be a bit cleaner in my vision. Ultimately I'd like to have that Position as an enum as well. It would be a large enum, but make interacting with our engine completely safe then, instead of just whatever strings being passed in that we want.

**Comment by Alemkin** [comment]
Put out a pull request too

**Comment by frodare** [comment]
I like it.  We could use one enum for the column and an int for row.  That way the enum would only hold eight values {a, b, c, d, e, f, g, h}.  We could use an enum for row too i guess, something like {ROW_1, ROW_2 ...}

**Comment by Alemkin** [comment]
Alright I added another pull request with the update. With that you should be good to just start hooking into it.

**Comment by frodare** [comment]
Yup, looks good. Feel free to push directly to the repo now if you like, PRs are fine too though.

**Comment by Alemkin** [comment]
Alright cool

**Comment by Alemkin** [comment]
Ah, before we get started, we should change that return type for get moves to be a list of position objects, instead of string, which holds the coordinate letter and number, as a way to pair them, and make reading the result easier.

**Comment by frodare** [comment]
Agreed

**Comment by Alemkin** [comment]
Should I make that a static nested class in the ChessPieceState?

**Comment by frodare** [comment]
Sure, we can always move it later if needed

**Comment by Alemkin** [comment]
Okay, should be good to go now
